### ISSUE TITLE
Web Demo Results in IndexError

### ISSUE THREAD

**Issue by LeeJoonJie** [blmoistawinde/KPCNet#1]
I tried running the web demo as instructed in the ReadMe but ran into the error shown below after pressing the "Question" button. I am using macOS. I would appreciate any advice on how to fix this.

![Screenshot 2021-05-09 at 6 19 27 PM](https://user-images.githubusercontent.com/48320865/117568547-71ef9400-b0f3-11eb-9aa0-99dbc5911843.png)

**Comment by blmoistawinde** [comment]
Problem of the `/` sometimes producing float result that is invalid for indices, now fixed.

**Comment by LeeJoonJie** [comment]
It works now. Thanks!
