### ISSUE TITLE
I tried running the web demo as instructed in the ReadMe but ran into the error shown below after pressing the "Question" button. I am using macOS. I would appreciate any advice on how to fix this.

### ISSUE THREAD

**Issue by ddy-ddy** [blmoistawinde/KPCNet#2]
I tried running the web demo as instructed in the ReadMe but ran into the error shown below after pressing the "Question" button. I am using macOS. I would appreciate any advice on how to fix this.
![截屏2021-06-04 下午8 56 20](https://user-images.githubusercontent.com/58058861/120804514-52734c00-c577-11eb-8762-85672846cdd0.png)

**Comment by blmoistawinde** [comment]
I can't reproduce this bug on my Windows/Linux machine, but I guess it is the problem of variable scope, as the variable is defined outside and below the function where it is used. So I tried to pre-define them at the top. Please try if this can fix your issue.
