### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by ddy-ddy** [blmoistawinde/KPCNet#3]
Hello.author.I am very interesting in your paper.and I want to train the model called "keyword predictor" and "KPCNet".I would like to know how much time you have spent training these two models and what configuration computers are running on?I am so appreciate if you could reply my answer.have a good day.

**Comment by blmoistawinde** [comment]
My configuration was on Nvidia 2080Ti. The keyword predictor should be able to converge in about 1 or 2 hours, and the generation model needs about a day.
