### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ddy-ddy** [blmoistawinde/KPCNet#4]
hello,author.i seem to have found a bug.I don't know if it was caused by my improper operation.
I run predict.py with these parameter。
`python predict.py	--test_context ./data/test_context.txt \
                  --test_ques ./data/test_ques.txt \
                  --test_ids ./data/test_asin.txt \
                  --word_embeddings ./data/word_embeddings.p \
                  --vocab ./data/vocab.p \
                  --kwd_vocab ./data/train_kwd_vocab.txt \
                  --load_models_dir ./ckpt/##YOUR_MODEL##.models \
                  --load_hparams_dir ./hparams/##YOUR_MODEL##.json \
                  --load_filter_dir ./data/kwd_filter_dict.json \
                  --out_dir ./output \
                  --threshold 0.075 \
                  --batch_size 128 \
                  --diverse_beam \
                  --save_all_beam \
                  --beam_size 6 \
                  --diverse_group 3 \
                  --diverse_lambda 0.4 \
                  --batch_size 128`
But it got this error.
![截屏2021-07-07 下午2 10 58](https://user-images.githubusercontent.com/58058861/124709299-e5fcbb80-df2d-11eb-92f9-75e06b8291cc.png)
![截屏2021-07-07 下午2 10 39](https://user-images.githubusercontent.com/58058861/124709312-e85f1580-df2d-11eb-9037-1ba09d68eb14.png)

**Comment by blmoistawinde** [comment]
Should be similar as https://github.com/blmoistawinde/KPCNet/issues/1 , seems the current pytorch version don't convert index to integer as my original version, now fixed.

**Comment by ddy-ddy** [comment]
> Should be similar as #1 , seems the current pytorch version don't convert index to integer as my original version, now fixed.

ok，thank you so much.
