### ISSUE TITLE
data

### ISSUE THREAD

**Issue by ddy-ddy** [blmoistawinde/KPCNet#6]
hello,author.i want to know how to generate the file "data/train_kwd_vocab.txt".Does it exist with the original data set? Or is it an outside lexicon extracted from all the questions?
![截屏2021-07-10 下午9 51 52](https://user-images.githubusercontent.com/58058861/125165427-67bc4580-e1c9-11eb-9b43-0ae509764855.png)

**Comment by blmoistawinde** [comment]
please refer to https://github.com/blmoistawinde/KPCNet/blob/main/prepare/build_kwd_vocab.py for the generation of the vocabulary, other keyword related codes are also in the directory.

**Comment by ddy-ddy** [comment]
> please refer to https://github.com/blmoistawinde/KPCNet/blob/main/prepare/build_kwd_vocab.py for the generation of the vocabulary, other keyword related codes are also in the directory.

get it.thank you so much.
